### ISSUE TITLE
multi users

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [otsuarez/mkdocs_auth#5]
How to add others users? is it possible

**Comment by otsuarez** [comment]
It is possible. The simplest way would be to add them to the [theme_addons/basic_auth.inc](https://github.com/otsuarez/mkdocs_auth/blob/master/theme_addons/basic_auth.inc#L2) file. 

Not the best approach since you'll be hardcoding sensitive data on the php code, but it's the fastest way. 

A better way would be to change the `config.extra` section of the `mkdocs.yml` file to accomodate for a list of users and to update the `theme_addons/basic_auth.inc` mentioned line to read the list of users from the yaml file.
